receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:  

exporters:
  awscloudwatchlogs:
    region: ${AWS_REGION}
    log_group_name: "${MY_SD_NUMBER}/o11y-lab/logs"
    log_stream_name: "${MY_SD_NUMBER}/o11y-lab/stream"
    log_retention: 7
  awsemf:
    region: ${AWS_REGION}
    log_group_name: ${MY_SD_NUMBER}/o11y-lab/metrics
    namespace: "${MY_SD_NUMBER}-o11y-lab-metrics"
    log_retention: 7
  awsxray:
    region: ${AWS_REGION}

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
       receivers: [otlp]
       processors: [batch]
       exporters: [awscloudwatchlogs]
    metrics:
       receivers: [otlp]
       processors: [batch]
       exporters: [awsemf] 
    traces:
       receivers: [otlp]
       processors: [batch]
       exporters: [awsxray]